import type { Store } from './store.js';
export function loadDemo(store: Store) {
  const companies = [
    {
      name: 'Forma Studio',
      industry: 'Design tools',
      location: 'Europe',
      size: '11–50',
      tags: ['SaaS', 'Design'],
      website: 'https://example.com/forma',
    },
    {
      name: 'Northstar Labs',
      industry: 'Developer tools',
      location: 'Worldwide',
      size: '51–200',
      tags: ['DevTools', 'Open source'],
      website: 'https://example.com/northstar',
    },
    {
      name: 'Monogram',
      industry: 'Fintech',
      location: 'Berlin, Germany',
      size: '51–200',
      tags: ['Fintech', 'B2B'],
      website: 'https://example.com/monogram',
    },
    {
      name: 'Orbit Health',
      industry: 'Healthtech',
      location: 'Europe',
      size: '201–500',
      tags: ['Healthtech'],
      website: 'https://example.com/orbit',
    },
    {
      name: 'Evergreen',
      industry: 'Climate tech',
      location: 'Amsterdam',
      size: '11–50',
      tags: ['Climate', 'B2B'],
      website: 'https://example.com/evergreen',
    },
  ];
  const jobs = [
    {
      title: 'Senior Product Designer',
      company: 'Forma Studio',
      location: 'Europe · GMT ±3',
      workMode: 'remote',
      seniority: 'senior',
      salaryMin: 75000,
      salaryMax: 95000,
      tags: ['Product design', 'Figma', 'SaaS'],
      favorite: true,
      stage: 'saved',
    },
    {
      title: 'Frontend Engineer',
      company: 'Northstar Labs',
      location: 'Worldwide',
      workMode: 'remote',
      seniority: 'middle',
      salaryMin: 70000,
      salaryMax: 100000,
      tags: ['React', 'TypeScript', 'DevTools'],
      stage: 'new',
    },
    {
      title: 'Product Manager',
      company: 'Monogram',
      location: 'Berlin, Germany',
      workMode: 'hybrid',
      seniority: 'senior',
      salaryMin: 85000,
      salaryMax: 110000,
      tags: ['Strategy', 'Fintech', 'B2B'],
      stage: 'interview',
      favorite: true,
      followUp: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
    },
    {
      title: 'Senior Full Stack Engineer',
      company: 'Orbit Health',
      location: 'Europe',
      workMode: 'remote',
      seniority: 'senior',
      salaryMin: 80000,
      salaryMax: 105000,
      tags: ['React', 'Node.js', 'TypeScript'],
      stage: 'applied',
    },
    {
      title: 'Brand & Visual Designer',
      company: 'Evergreen',
      location: 'Amsterdam, Netherlands',
      workMode: 'hybrid',
      seniority: 'middle',
      salaryMin: 55000,
      salaryMax: 75000,
      tags: ['Brand', 'Design systems'],
      stage: 'new',
    },
    {
      title: 'Staff Software Engineer',
      company: 'Northstar Labs',
      location: 'Worldwide',
      workMode: 'remote',
      seniority: 'lead',
      salaryMin: 120000,
      salaryMax: 160000,
      tags: ['Architecture', 'TypeScript', 'Platform'],
      stage: 'offer',
    },
  ];
  return store.importData({
    companies: companies.map((c) => ({
      ...c,
      demo: true,
      notes: 'Вымышленная компания для знакомства с интерфейсом.',
    })),
    jobs: jobs.map((j, i) => ({
      ...j,
      demo: true,
      source: 'demo',
      url: `https://example.com/demo/jobs/${i}`,
      currency: 'EUR',
      salaryPeriod: 'year',
      description:
        'Это демонстрационная вакансия вымышленной компании.\n\nЗдесь будет описание роли, задачи, требования к опыту и условия работы из первоисточника. Можно менять этап воронки, сохранять заметки и назначать дату следующего действия.',
      publishedAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  });
}
